### ISSUE TITLE
ParallelMeshGeneration in examples doesn't work

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [avr-aics-riken/BCMTools#15]
I have compiled BCMTools on CentOS 6.6 with the following options:

cmake -DINSTALL_DIR=$HOME/work/BCM/BCMTools/build/install \
      -Denable_OPENMP=yes \
      -Dwith_MPI=yes \
      -Dwith_example=yes \
      -Dreal_type=double \
      -Dwith_TP=$HOME/work/BCM/TextParser/build/install 
      -Dwith_PL=$HOME/work/BCM/Polylib/build/install \
      -Dwith_CUT=$HOME/work/BCM/Cutlib/build/install \
      -Denable_LARGE_BLOCK=no \
      -Dwith_SILO=$HOME/work/BCM/silo-4.10.2/install ..

However, I encountered the following problem:

[ 25%] Linking CXX executable mesh-gen
CMakeFiles/mesh-gen.dir/ParallelMeshGeneration/main.cpp.o: In function `PolygonBBoxDivider::operator()(Pedigree const&)':
main.cpp:(.text._ZN18PolygonBBoxDividerclERK8Pedigree[PolygonBBoxDivider::operator()(Pedigree const&)]+0x6b1): undefined reference to `PolylibNS::Polylib::search_polygons(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, Vec3class::Vec3<double>, Vec3class::Vec3<double>, bool) const'
$HOME/work/BCM/BCMTools/build/src/libBCMmpi.a(BCMPolylib.cpp.o): In function `PolylibNS::BCMPolylib::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, float)':
BCMPolylib.cpp:(.text+0x81): undefined reference to `PolylibNS::Polylib::load_polygons(bool, PolylibNS::ID_FORMAT, double)'
$HOME/work/BCM/BCMTools/build/src/libBCMmpi.a(BCMPolylib.cpp.o): In function `PolylibNS::BCMPolylib::set_bounding_box(int, Vec3class::Vec3<double> const&, Vec3class::Vec3<double> const&)':
BCMPolylib.cpp:(.text+0x38e): undefined reference to `PolylibNS::BBox::add(Vec3class::Vec3<double> const&)'
BCMPolylib.cpp:(.text+0x3a2): undefined reference to `PolylibNS::BBox::add(Vec3class::Vec3<double> const&)'
BCMPolylib.cpp:(.text+0x460): undefined reference to `PolylibNS::BBox::add(Vec3class::Vec3<double> const&)'
BCMPolylib.cpp:(.text+0x46b): undefined reference to `PolylibNS::BBox::add(Vec3class::Vec3<double> const&)'
collect2: ld returned 1 exit status
make[2]: *** [examples/mesh-gen] Error 1
make[1]: *** [examples/CMakeFiles/mesh-gen.dir/all] Error 2
make: *** [all] Error 2

Does anybody have any suggestion? I really need your help!

Thanks in advance,

**Comment by kenoogl** [comment]
Dear Kenichiro,
Thanks for your issue report. Currently, I confirmed Cmake package of BCMTools on my Mac, and it works.
Please give me a while to set up a CentOS 6.6 environment and to confirm the build process on it.

**Comment by Kenichiro-Yoshimi** [comment]
Thanks, for your answer.

My environment is the following:
OS : CentOS release 6.6
CPU: Xeon E5-2643v3(6core, 3,4GHz) * 2CPU
RAM: 512GB
HDD: 3.0TB/7200rpm/SATA

gcc version 4.4.7
openmpi-1.10.2
cmake-3.5.2
silo-4.10.2
HDF5 1.8.17

And my building process is the following:
1. TextParser, Cutlib and Polylib are setup with CMake options based on the instruction "INTEL/GNU compiler" of each github Readme.md. And then to make and install are completed successfully.
 Installation locations:
$HOME/work/BCM/Polylib/build/install/
$HOME/work/BCM/TextParser/build/install/
$HOME/work/BCM/Cutlib/build/install

2. BCMTools is also built using CMake options of "INTEL/GNU compiler". However in make process, 
 I need to add required paths such as below since some error messages appear due to the lacking:

   i. src/CMakeFiles/BCMmpi.dir/flags.make
     -I/usr/local/openmpi-1.10.2/include

   ii. Utils/CMakeFiles/BCMconfig.dir/flags.make
     -I/usr/local/openmpi-1.10.2/include
     -I/home/yoshimi/work/BCM/Polylib/build/install/include

   iii. examples/CMakeFiles/mesh-gen.dir/flags.make
     -I/usr/local/openmpi-1.10.2/include

   iv. examples/CMakeFiles/mesh-gen.dir/link.txt
     -L/usr/local/openmpi-1.10.2/lib -lmpi_cxx -lmpi

After these settings are applied, the next make command causes the previous error.
Is there any method to solve such a situation?

Best Regards,

**Comment by kenoogl** [comment]
I've just prepared the same environment as you tested on a docker container and confirm that our libraries works on it. I made a test package for you so that you can evaluate. Please visit gitlab (NOT GitHub!) https://gitlab.com/riit-ku/BCMTools-package and pick tarball. Also, I will attach the install log file here.  Best of luck to you!
[install_log.txt](https://github.com/avr-aics-riken/BCMTools/files/895542/install_log.txt)

**Comment by Kenichiro-Yoshimi** [comment]
Thanks, that worked. I really appreciate it. I'll try to start the example on how to use the PolygonBBoxDivider class.
Thanks in advance for your kind help.
